before_script:
  - cd presentation/06-gitlab/container

build:
  stage: build
  script:
    - make docker-build

cd:
  stage: deploy
  script:
    # yc iam key create --service-account-name robot-presentation --folder-id b1gmkppivuuf7k133tv0 -o key.json
    - echo $DOCKER_PASSWORD | docker login --username json_key --password-stdin cr.yandex
    - make docker-push

ci:
  stage: deploy
  needs:
    - cd
  script:
    - kubectl -n shbr rollout restart 'deployment/shbr-echo'