- hosts: "all"
  tasks:
    - name: "pkgs : apt-get"
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - fish
          - net-tools
    - name: "pkgs : apt-get : for minikube"
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        state: present
        name:
          - iptables
          - conntrack

    - name: "docker : key"
      become: true
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

    - name: "docker : repo"
      become: true
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: "docker : pkg"
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose
          - containerd.io

    - name: "docker : service"
      service:
        name: docker
        enabled: yes
        state: started

    - name: "docker : user in group docker"
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/fish
        groups: docker
        append: yes
