apiVersion: apps/v1
kind: Deployment
metadata:
  name: shbr-echo-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shbr-echo
  template:
    metadata:
      labels:
        app: shbr-echo
        version: "1"
    spec:
      containers:
        - image: cr.yandex/crpo6t63ueuf0jf6tm5a/01-package-docker:latest
          name: shbr-echo
          env:
            - name: PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always
