- hosts: "all"
  connection: local
  tasks:
    - name: "shbr-echo : container"
      docker_container:
        name: "03-run-ansible"
        restart_policy: 'always'
        state: 'started'
        image: 'cr.yandex/crpo6t63ueuf0jf6tm5a/01-package-docker:latest'
        env:
          LANG: python
        ports:
          - "10000:10000"
